### PR TITLE
Variables added in a $let do not persist outside of that $let

### LINKED ISSUE #473: [javascript] $let leaks assignments
Given a template:
```yaml
- $let:
    outlets: [1,2,3]
  in: {$eval: "outlets"}
- {$eval: "outlets"}
```

I would expect the results to be:
```yaml
# Error:
# InterpreterError at template[1]: unknown context value outlets
```

Instead it is:
```yaml
- &ref_0
  - 1
  - 2
  - 3
- *ref_0
```

Above tested with the online playground.  I also tested it in python, which does the correct thing:
```python
>>> import jsone
>>> context={}
>>> template= [ { "$let": { "outlets": [1,2,3] }, "in": { "$eval": "outlets" } }, {"$eval": "outlets"} ]
>>> print(jsone.render(template, context))                                                           Traceback (most recent call last):
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/interpreter.py", line 164, in visit_ContextValue
    contextValue = self.context[node.token.value]
                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'outlets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/__init__.py", line 20, in render
    rv = renderValue(template, full_context)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/render.py", line 447, in renderValue
    return list(updated())
           ^^^^^^^^^^^^^^^
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/render.py", line 440, in updated
    v = renderValue(e, context)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/render.py", line 412, in renderValue
    return operators[matches[0]](template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/render.py", line 122, in eval
    return parse(template['$eval'], context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/render.py", line 59, in parse
    result = interp.interpret(tree)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/interpreter.py", line 192, in interpret
    return self.visit(tree)
           ^^^^^^^^^^^^^^^^
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/interpreter.py", line 17, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/interpreter.py", line 166, in visit_ContextValue
    raise InterpreterError(
jsone.shared.InterpreterError: InterpreterError at template[1]: unknown context value outlets
```

### PR DESCRIPTION
**Pull request by tadpol**
Fixes #473

For JavaScript, Variables added in a `$let` do not persist outside of that `$let` any more

# Checklist

Before submitting a pull request, please check the following:

* [X] All tests pass for you on your machine for all implementations (all implementations must behave identically)
* [X] New tests have been added for any new functionality or to prevent regressions of a bugfix
* [X] Added a short description of the change to `newsfragments/$issue.bugfix` (for fixes) or `.feature` (for new features) or `.doc` (for documentation-only changes)

### CODE REVIEW

File: js/test/misc_test.js [hunk 1]
```diff
@@ -38,4 +38,16 @@ suite('misc', function() {
...
+    let template = {
+      $let: {
+        foo: 'bar',
+        baz: 'qux',
+      },
+      $eval: 'foo',
+    };
+
+    assume(() => jsone(template, {})).throws();
+  });
```
Comment (djmitche) [inline js/test/misc_test.js:52]: This is a good test, but we should test cross-platform by adding this case to `specification.yml` instead.

**Review by djmitche — CHANGES_REQUESTED** [review]
Thanks for the fix! Can you update the title of the PR to describe what it's fixing?

**Review by djmitche — APPROVED** [review]
Awesome, thank you!
